services:
    _defaults:
        public: false
        autowire: false
        autoconfigure: false

    ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpApiClientProvider: ~

    ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpManagerInterface: '@ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpManager'
    ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpManager:
        arguments:
            $mailChimpApiClientProvider: '@ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpApiClientProvider'

    ThreeBRS\SyliusMailChimpPlugin\Service\ChannelMailChimpSettingsProviderInterface: '@ThreeBRS\SyliusMailChimpPlugin\Service\ChannelMailChimpSettingsProvider'
    ThreeBRS\SyliusMailChimpPlugin\Service\ChannelMailChimpSettingsProvider:
        arguments:
            $channelContext: '@sylius.context.channel.request_based'

    ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpChannelSubscriberInterface: '@ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpChannelSubscriber'
    ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpChannelSubscriber:
        arguments:
            $shopperContext: '@sylius.context.shopper'
            $channelMailChimpSettingsProvider: '@ThreeBRS\SyliusMailChimpPlugin\Service\ChannelMailChimpSettingsProvider'
            $mailChimpManager: '@ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpManager'

    ThreeBRS\SyliusMailChimpPlugin\Model\CustomerListener:
        arguments:
            $channelMailChimpSettingsProvider: '@ThreeBRS\SyliusMailChimpPlugin\Service\ChannelMailChimpSettingsProvider'
            $mailChimpChannelSubscriber: '@ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpChannelSubscriber'
            $logger: '@logger'
        tags:
            - name: kernel.event_listener
              event: sylius.order.post_complete
              method: syncSubscriptionToMailChimp
            - name: kernel.event_listener
              event: sylius.customer.post_register
              method: syncSubscriptionToMailChimp
            - name: kernel.event_listener
              event: sylius.customer.post_create
              method: syncSubscriptionToMailChimp
            - name: kernel.event_listener
              event: sylius.customer.post_update
              method: syncSubscriptionToMailChimp
            - name: kernel.event_listener
              event: security.interactive_login
              method: syncSubscriptionStateFromMailChimp

    ThreeBRS\SyliusMailChimpPlugin\Form\Extension\NewsletterSubscribeTypeExtension:
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerCheckoutGuestType

    ThreeBRS\SyliusMailChimpPlugin\Form\Extension\MailChimpChannelTypeExtension:
        arguments:
            $mailChimpManager: '@ThreeBRS\SyliusMailChimpPlugin\Service\MailChimpManager'
        tags:
            - name: form.type_extension
              extended_type: Sylius\Bundle\ChannelBundle\Form\Type\ChannelType
